
import pptxgen from "pptxgenjs";
import { Slide } from "@/types/presentation";

export const exportToPptx = async (slides: Slide[], topic: string) => {
    const pres = new pptxgen();
    pres.title = topic;
    pres.subject = "Generated by Slide Weaver";
    pres.layout = "LAYOUT_16x9";

    const COLORS = {
        PRIMARY: "007AFF",
        TEXT_MAIN: "1d1d1f",
        TEXT_SUB: "64748B",
        BG_GRID: "FFFFFF",
        SUCCESS: "007AFF",
        DANGER: "DC2626",
        CARD_BG: "F1F5F9" // Slate-100/Secondary
    };
    const MAIN_FONT = "Segoe UI";
    const TAG_RADIUS = 1.0;

    // --- Image Embedding Helper --- (Unchanged)
    const embedImage = async (path: string): Promise<string> => {
        if (!path) return "";
        const url = path.startsWith('http') ? path : `${window.location.origin}${path}`;
        try {
            const response = await fetch(url);
            const blob = await response.blob();
            return new Promise((resolve) => {
                const reader = new FileReader();
                reader.onloadend = () => resolve(reader.result as string);
                reader.onerror = () => { console.error("Base64 read error"); resolve(""); };
                reader.readAsDataURL(blob);
            });
        } catch (e) {
            console.error("Failed to embed image:", path, e);
            return "";
        }
    };

    // --- GRID GENERATION --- (Unchanged)
    const generateFullGridBackground = (): string => {
        const width = 960;
        const height = 540;
        const gridSize = 40;
        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        if (!ctx) return "";
        ctx.fillStyle = "#FFFFFF";
        ctx.fillRect(0, 0, width, height);
        ctx.strokeStyle = "rgba(0, 122, 255, 0.06)";
        ctx.lineWidth = 1;
        ctx.beginPath();
        for (let x = 0; x <= width; x += gridSize) { ctx.moveTo(x + 0.5, 0); ctx.lineTo(x + 0.5, height); }
        ctx.stroke();
        ctx.beginPath();
        for (let y = 0; y <= height; y += gridSize) { ctx.moveTo(0, y + 0.5); ctx.lineTo(width, y + 0.5); }
        ctx.stroke();
        return canvas.toDataURL('image/png');
    };
    const GRID_FULL_IMG = generateFullGridBackground();

    // --- Master Slide Definition --- (Unchanged)
    pres.defineSlideMaster({
        title: "MASTER_SLIDE",
        background: { data: GRID_FULL_IMG },
        objects: [
            { text: { text: "Career", options: { x: 7.0, y: 0.2, w: 2.0, h: 0.5, fontSize: 18, fontFace: "Arial Black", bold: true, color: COLORS.TEXT_MAIN, align: "right" } } },
            { text: { text: "247", options: { x: 9.1, y: 0.2, w: 0.6, h: 0.4, fontSize: 14, fontFace: "Arial Black", bold: true, color: "FFFFFF", fill: { color: COLORS.PRIMARY }, align: "center", rectRadius: 0.1 } } },
            { placeholder: { options: { name: "slideNumber", type: "body", x: 9.0, y: 5.2, w: 0.8, h: 0.3, fontSize: 10, color: COLORS.TEXT_SUB, align: "right" }, text: "" } }
        ]
    });

    // --- Process Slides ---
    for (const [index, slideContent] of slides.entries()) {
        const slide = pres.addSlide({ masterName: "MASTER_SLIDE" });
        slide.addText(`${index + 1}`, { x: 9.4, y: 5.2, w: 0.4, h: 0.3, fontSize: 10, color: COLORS.TEXT_SUB, fontFace: "Arial", align: "right" });

        const { layoutId, content } = slideContent;
        const title = (content.title as string) || "Untitled";
        const subtitle = content.subtitle as string;
        const moduleTag = (content.moduleTag as string) || "Module 4";
        const topicTag = (content.topicTag as string) || "ai";

        // Pre-embed images
        let mainImgData = "";
        if (layoutId === 'title-hero') mainImgData = await embedImage("/illustrations/slide1_hero.png");
        else if (layoutId === 'section-title' || layoutId === 'introduction-objectives') mainImgData = await embedImage("/illustrations/thinking_girl.png");
        else if (layoutId === 'content-image') {
            const imgPath = title.toLowerCase().includes('introduction') ? "/illustrations/introduction_person.png" : "/illustrations/illustration5.png";
            mainImgData = await embedImage(imgPath);
        } else if (layoutId === 'timeline-facts') mainImgData = await embedImage("/illustrations/key_facts.png");
        else if (layoutId === 'executive-summary') mainImgData = await embedImage("/illustrations/executive_summary.png");

        // --- HERO SLIDES ---
        if (layoutId === 'title-hero') {
            slide.addText(moduleTag, { shape: pres.ShapeType.roundRect, x: 0.5, y: 0.5, w: 1.5, h: 0.4, fontSize: 10, bold: true, color: "FFFFFF", fill: { color: COLORS.PRIMARY }, align: "center", rectRadius: TAG_RADIUS, fontFace: MAIN_FONT });
            slide.addShape(pres.ShapeType.roundRect, { x: 2.2, y: 0.5, w: 1.0, h: 0.4, fill: { color: "FFFFFF" }, line: { color: COLORS.PRIMARY, width: 1.5 }, rectRadius: TAG_RADIUS });
            slide.addText(topicTag, { x: 2.2, y: 0.5, w: 1.0, h: 0.4, fontSize: 10, color: "111827", bold: true, align: "center", fontFace: MAIN_FONT });
            slide.addText(title, { x: 0.5, y: 2.0, w: 4.5, h: 1.5, fontSize: 54, bold: true, color: COLORS.TEXT_MAIN, align: "left", fontFace: "Arial Black", valign: "bottom" });
            if (subtitle) slide.addText(subtitle, { x: 0.5, y: 3.5, w: 4.5, h: 1, fontSize: 24, color: COLORS.TEXT_SUB, align: "left", fontFace: MAIN_FONT, valign: "top" });
            if (mainImgData) slide.addImage({ data: mainImgData, x: 5.0, y: 1.0, w: 4.5, h: 4.0, sizing: { type: "contain", w: 4.5, h: 4.0 } });
        }
        else if (layoutId === 'thank-you') {
            slide.addText(title, { x: "10%", y: "35%", w: "80%", h: 1.5, fontSize: 60, bold: true, color: COLORS.TEXT_MAIN, align: "center", fontFace: "Arial Black" });
            slide.addText(subtitle || "We look forward to working with you.", { x: "15%", y: "55%", w: "70%", h: 1, fontSize: 20, color: COLORS.TEXT_SUB, align: "center", fontFace: MAIN_FONT });
        }
        else if (layoutId === 'qna-final') {
            slide.addText(title, { x: 0.5, y: 0.5, w: 9, h: 0.8, fontSize: 32, bold: true, color: COLORS.PRIMARY, fontFace: "Arial Black", align: "center" });
            if (content.reflectionQuestion) slide.addText(content.reflectionQuestion as string, { x: 1.5, y: 2.0, w: 7, h: 1.5, fontSize: 24, color: COLORS.TEXT_MAIN, italic: true, align: "center", fill: { color: "F8FAFC" }, fontFace: MAIN_FONT });
            if (content.callToAction) slide.addText(content.callToAction as string, { x: 2, y: 4.0, w: 6, h: 0.5, fontSize: 18, color: COLORS.TEXT_SUB, align: "center", fontFace: MAIN_FONT });
        }
        else {
            // --- STANDARD SLIDES ---
            const headerY = 0.3;
            slide.addText(title, { x: 0.5, y: headerY, w: 9, h: 0.7, fontSize: 36, bold: true, color: COLORS.PRIMARY, fontFace: "Arial Black", align: "left" });
            if (subtitle) slide.addText(subtitle, { x: 0.5, y: 0.9, w: 9, h: 0.4, fontSize: 16, color: COLORS.TEXT_SUB, fontFace: MAIN_FONT, align: "left" });
            slide.addShape(pres.ShapeType.rect, { x: 0.5, y: 1.1, w: 1.5, h: 0.08, fill: { color: COLORS.PRIMARY } });

            // Tags (Left, Below Line)
            const tagY = 1.3;
            slide.addText(moduleTag, { shape: pres.ShapeType.roundRect, x: 0.5, y: tagY, w: 1.5, h: 0.35, fontSize: 10, color: "FFFFFF", bold: true, fill: { color: COLORS.PRIMARY }, align: "center", rectRadius: TAG_RADIUS, fontFace: MAIN_FONT });
            slide.addShape(pres.ShapeType.roundRect, { x: 2.2, y: tagY, w: Math.min(3, topicTag.length * 0.15 + 0.5), h: 0.35, fill: { color: "FFFFFF" }, line: { color: COLORS.PRIMARY, width: 1.5 }, rectRadius: TAG_RADIUS });
            slide.addText(topicTag, { x: 2.2, y: tagY, w: Math.min(3, topicTag.length * 0.15 + 0.5), h: 0.35, fontSize: 10, color: "111827", bold: true, align: "center", fontFace: MAIN_FONT });

            // --- CONTENT BODY ---
            const contentY = 2.0;

            switch (layoutId) {
                // ... (Keep existing simple layouts) ...
                case 'section-title':
                case 'introduction-objectives':
                    slide.addText(content.body as string, { x: 0.5, y: contentY, w: 4.8, h: 3, fontSize: 16, color: COLORS.TEXT_MAIN, valign: "top", fontFace: MAIN_FONT });
                    if (mainImgData) slide.addImage({ data: mainImgData, x: 5.8, y: contentY, w: 3.8, h: 3, sizing: { type: "contain", w: 3.8, h: 3 } });
                    break;

                case 'content-image':
                    slide.addText(content.body as string, { x: 0.5, y: contentY, w: 4.8, h: 3, fontSize: 16, color: COLORS.TEXT_MAIN, valign: "top", fontFace: MAIN_FONT });
                    if (content.callout) slide.addText(content.callout as string, { x: 0.5, y: 4.2, w: 4.8, h: 0.8, fontSize: 12, color: "1E40AF", fill: { color: "EFF6FF" }, inset: 0.1, fontFace: MAIN_FONT });
                    if (mainImgData) slide.addImage({ data: mainImgData, x: 5.8, y: contentY, w: 3.8, h: 3, sizing: { type: "contain", w: 3.8, h: 3 } });
                    break;

                case 'deep-dive':
                    // Keep Deep Dive same as verified? Assuming it follows standard pattern.
                    // But let's apply Card Style to deep dive too if needed. 
                    // For now, keep as text columns to be safe / aligned with previous.
                    if (content.leftTitle) {
                        slide.addText(content.leftTitle as string, { x: 0.5, y: contentY, w: 4, h: 0.4, bold: true, color: COLORS.PRIMARY, fontFace: MAIN_FONT });
                        slide.addText(content.leftContent as string || "Content", { x: 0.5, y: contentY + 0.4, w: 4, h: 2, fontSize: 14, color: COLORS.TEXT_MAIN, fontFace: MAIN_FONT });
                        slide.addText(content.rightTitle as string, { x: 5, y: contentY, w: 4, h: 0.4, bold: true, color: COLORS.PRIMARY, fontFace: MAIN_FONT });
                        const rItems = (content.rightItems as string[]) || [];
                        rItems.forEach((it, i) => slide.addText(`• ${it}`, { x: 5, y: contentY + 0.4 + (i * 0.35), w: 4, h: 0.35, fontSize: 14, color: COLORS.TEXT_MAIN, fontFace: MAIN_FONT }));
                    } else {
                        slide.addText(content.body as string || "Deep Dive Content", { x: 0.5, y: contentY, w: 9, h: 3, fontSize: 16, color: COLORS.TEXT_MAIN, fontFace: MAIN_FONT });
                    }
                    break;

                case 'two-column-cards':
                case 'dos-donts-comparison':
                case 'dos-donts-list':
                    // --- CARD LAYOUT IMPLEMENTATION ---
                    if (content.listType) {
                        // List
                        (content.items as string[])?.forEach((item, i) => {
                            slide.addText(item, { x: 0.8, y: contentY + (i * 0.5), w: 8, h: 0.4, fontSize: 16, color: COLORS.TEXT_MAIN, bullet: true, fontFace: MAIN_FONT });
                        });
                    } else {
                        // Comparison: Two Internal Cards with Pill Headers

                        // LEFT CARD
                        // 1. Background
                        slide.addShape(pres.ShapeType.roundRect, {
                            x: 0.5, y: contentY, w: 4.4, h: 3.0,
                            fill: { color: COLORS.CARD_BG }, rectRadius: 0.5, line: { color: "E2E8F0" }
                        });
                        // 2. Pill Header (Blue)
                        slide.addText(content.leftTitle || "Benefits", {
                            shape: pres.ShapeType.roundRect,
                            x: 0.7, y: contentY + 0.2, w: 1.5, h: 0.4, // Small internal pill
                            bold: true, fill: { color: COLORS.PRIMARY }, color: "FFFFFF", align: "center", fontFace: MAIN_FONT, fontSize: 12, rectRadius: 1.0
                        });
                        // 3. Content
                        const lefts = (content.doItems || content.leftItems || []) as string[];
                        lefts.forEach((it, i) => slide.addText(`• ${it}`, { x: 0.7, y: contentY + 0.8 + (i * 0.35), w: 4.0, h: 0.35, color: COLORS.TEXT_MAIN, fontFace: MAIN_FONT, fontSize: 14 }));

                        // RIGHT CARD
                        // 1. Background
                        slide.addShape(pres.ShapeType.roundRect, {
                            x: 5.1, y: contentY, w: 4.4, h: 3.0,
                            fill: { color: COLORS.CARD_BG }, rectRadius: 0.5, line: { color: "E2E8F0" }
                        });
                        // 2. Pill Header (Red if "Challenges"/"Don'ts", else Blue)
                        const rTitle = content.rightTitle || "Challenges";
                        const isRed = rTitle.toLowerCase().includes("challenge") || rTitle.toLowerCase().includes("don");
                        const pillColor = isRed ? COLORS.DANGER : COLORS.PRIMARY;

                        slide.addText(rTitle, {
                            shape: pres.ShapeType.roundRect,
                            x: 5.3, y: contentY + 0.2, w: 1.5, h: 0.4, // Small internal pill
                            bold: true, fill: { color: pillColor }, color: "FFFFFF", align: "center", fontFace: MAIN_FONT, fontSize: 12, rectRadius: 1.0
                        });
                        // 3. Content
                        const rights = (content.dontItems || content.rightItems || []) as string[];
                        rights.forEach((it, i) => slide.addText(`• ${it}`, { x: 5.3, y: contentY + 0.8 + (i * 0.35), w: 4.0, h: 0.35, color: COLORS.TEXT_MAIN, fontFace: MAIN_FONT, fontSize: 14 }));
                    }
                    break;

                // (Keep Agenda, Timeline same as verified)
                default:
                    (content.items as string[])?.forEach((item, i) => slide.addText(`• ${item}`, { x: 0.8, y: contentY + (i * 0.5), w: 9, h: 0.4, fontSize: 16, color: COLORS.TEXT_MAIN, fontFace: MAIN_FONT }));
                    break;
            }
        }
    }

    return pres.writeFile({ fileName: `${topic.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pptx` });
};
